# Generated by Django 6.0.3 on 2026-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='analyst_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='cvss_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cve',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Crítica'), ('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja'), ('UNKNOWN', 'Desconocida')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='cve',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('INVESTIGATING', 'Investigando'), ('FALSE_POSITIVE', 'Falso Positivo'), ('RESOLVED', 'Resuelto')], default='PENDING', max_length=20),
        ),
    ]
