# Generated by Django 6.0.3 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilidades', '0002_cve_analyst_notes_cve_cvss_score_cve_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='cisa_date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='cisa_kev',
            field=models.BooleanField(default=False),
        ),
    ]
