# Generated by Django 6.0.3 on 2026-03-17 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilidades', '0003_cve_cisa_date_added_cve_cisa_kev'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IncidentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('author', models.CharField(default='Analista L1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_notes', to='vulnerabilidades.cve')),
            ],
        ),
    ]
