# Generated by Django 6.0.3 on 2026-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerabilidades', '0004_cve_created_at_incidentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='investigated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cve',
            name='is_false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cve',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
